### ISSUE TITLE
No longer works with v1.85

### ISSUE THREAD

**Issue by dziban303** [klensy/wt-tools#41]
I tried unpacking some ddsx files for the first time in a few months, and it didn't work. I was using 0.2.1.1, so I downloaded 0.2.1.3, and I get the same error.

```python-traceback
D:\War Thunder\UserSkins\!wttools-exe.win32>ddsx_unpack.exe abc.ddsx
Traceback (most recent call last):
  File "E:\Projs\wt-tools\venv_3.6.4\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "E:\Projs\wt-tools\venv_3.6.4\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "ddsx_unpack.py", line 102, in <module>
  File "ddsx_unpack.py", line 96, in main
  File "ddsx_unpack.py", line 70, in unpack_file
  File "ddsx_unpack.py", line 60, in unpack
zlib.error: Error -3 while decompressing data: incorrect header check
```

**Comment by klensy** [comment]
Yes, it's known issue #39, some of ddsx cant be unpacked.
