### ISSUE TITLE
Can not run any exe, Python complains about missing module

### ISSUE THREAD

**Issue by Horrifior** [klensy/wt-tools#69]
Trying to extract some economic data from aces.vromfs.bin, but failing:

- Freshly installed Python 3.7.9
- Was able to compile the ZIP downloaded from here.
- Had to install cx_Freeze, Click, zstandard, construct, requests manually via pip
- Still, stuff seems to be missing... wondering why I had to install so many modules manually in the first place?

C:\Program Files\wt_tools>vromfs_unpacker.exe
Traceback (most recent call last):
  File "C:\Users\GerdW\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
    module_init.run(name + "__main__")
  File "C:\Users\GerdW\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
    exec(code, module_main.__dict__)
  File "src/wt_tools/vromfs_unpacker.py", line 10, in <module>
  File "src/wt_tools\formats\vromfs_parser.py", line 4, in <module>
ImportError: cannot import name 'Embedded' from 'construct' (C:\Program Files\wt_tools\lib\library.zip\construct\__init__.pyc)

**Comment by OshidaBCF** [comment]
In case you aren't aware, Gaijin changed the format of *most* files that are extracted using klensy's tools. 

Klensy already fixed the vromfs extractor, but he is still working on the blk decrypter.

It's been a couple days now that klensy didn't updated any files, probably because everyone deserves holidays.

**Comment by Horrifior** [comment]
Dear all,

just to make a few things clear: 

- Everybody deserves vacation
- I never used klensies wt-tools before, I started today, so probably my issue is related to the installation of the proper python environment
- I can rule out it is a dataformat issue since it occurs (as you can see above) even if I am not given any kind of input file...

I would be happy to receive any kind of help or feedback about what I probably could have done wrong trying to get these tools running. Thank you in advance. No rush...

**Comment by OshidaBCF** [comment]
sorry I actually did forgot to read, when you downloaded all the files, there is 2. txt named requirements and dev requirements
I did failed that step because I can't use git properly, but you need to install those modules with the version. 
I don't know if higher version works.

**Comment by gszabi99** [comment]
@Horrifior workaround for your ImportError issue:
`pip install construct==2.9.52`
(Embedded is not part of construct after 2.10)
