### ISSUE TITLE
Is blk_unpack outdated?

### ISSUE THREAD

**Issue by KawasumiNana** [klensy/wt-tools#73]
Hi, boys. I compiled the latest wt-tools script in dev branch. vromfs_unpacker.exe worked perfectly, but blk_unpack.exe failed. It said

Traceback (most recent call last):
  File "src/wt_tools/blk_unpack.py", line 610, in unpack_dir
  File "src/wt_tools/blk_unpack.py", line 586, in unpack_file
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 1: illegal multibyte sequence

I really dont know whats going on there. Maybe my fault or is blk_unpack outdated?

Game version is 2.9.0.62

**Comment by diVineProportion** [comment]
The .vromfs.bin and .blk file structures have changed. [reddit post](https://www.reddit.com/r/Warthunder/comments/o5r4v1/heads_up_on_vrom_and_blk_format_changes_for_data/)

In the future please search both open and closed issues before starting a new one.

**Comment by Keksilton** [comment]
## Before posting an issue, please search through the existing ones.
Give a try to https://github.com/kotiq/wt-tools
Or my implementation over on https://github.com/Keksilton/WtTools
If you encounter issues with those - you should report them in the respective repo.
