### ISSUE TITLE
None of the tools work anymore

### ISSUE THREAD

**Issue by Aussie-Mantis** [klensy/wt-tools#74]
I'm using the windows version with the .exes. I'm getting the issue:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 33, in run
  File "src/wt_tools/vromfs_unpacker.py", line 121, in <module>
    # older blk versions
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\click\core.py", line 829, in __call__
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\click\core.py", line 782, in main
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\click\core.py", line 1066, in invoke
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\click\core.py", line 610, in invoke
  File "src/wt_tools/vromfs_unpacker.py", line 117, in main
    # print("unknown packed_type:{}, file:{}".format(packed_type,unpacked_filename))
  File "src/wt_tools/vromfs_unpacker.py", line 34, in unpack
    data = f.read()
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 263, in parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 281, in parse_stream
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 1898, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 2378, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 1898, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 2378, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 3511, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 1898, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 2378, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 4364, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 1898, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 2378, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 1898, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 2378, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 2137, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 286, in _parsereport
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 617, in _parse
  File "C:\hostedtoolcache\windows\Python\3.7.8\x64\lib\site-packages\construct\core.py", line 1337, in _decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by Keksilton** [comment]
## Before posting an issue, please search through the existing ones.
Give a try to https://github.com/kotiq/wt-tools
Or my implementation over on https://github.com/Keksilton/WtTools
If you encounter issues with those - you should report them in the respective repo.
